Implement and document the optional slack step

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -73,12 +73,39 @@ runs:
           SUBGRAPH=""
         fi
 
-        npx grafbase check ${{ inputs.project_ref }} --schema $SCHEMA_PATH $SUBGRAPH
+        set +e
+        echo 'check_errors<<STOPHERE' > "$GITHUB_OUTPUT"
+        npx grafbase check "${{ inputs.project_ref }}" --schema "$SCHEMA_PATH" $SUBGRAPH |& tee >(cat >&2) | jq --slurp --raw-input >> "$GITHUB_OUTPUT"
+        exit_code=${PIPESTATUS[0]}
+        echo 'STOPHERE' >> "$GITHUB_OUTPUT"
+
+        echo "Exiting with status $exit_code"
+        exit $exit_code
 
     - name: Post check errors to slack
       if: inputs.slack_incoming_webhook_url && failure()
       uses: slackapi/slack-github-action@v1.24.0
       with:
-        slack-message: "Composition check errors: Bears, beets, Battlestar Galactica."
+        payload: |
+          {
+            "text": "Schema checks failed for ${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
+            "blocks": [
+              {
+                "type": "section",
+                "text": {
+                  "type": "mrkdwn",
+                  "text": "Schema checks failed at ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
+                }
+              },
+              {
+                "type": "section",
+                "text": {
+                  "type": "mrkdwn",
+                  "text": ${{ steps.check.outputs.check_errors }}
+                }
+              }
+            ]
+          }
       env:
         SLACK_WEBHOOK_URL: ${{ inputs.slack_incoming_webhook_url }}
+        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
