Change all inputs from snake_case to kebab-case

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,18 +5,18 @@ branding:
   icon: activity
   color: green
 inputs:
-  grafbase_access_token:
+  grafbase-access-token:
     description: A Grafbase API access token. It can be created from the Grafbase dashboard.
     required: true
-  project_ref:
+  project-ref:
     description: "The account, project and (optional) branch of the schema to check against, in the format expected by the grafbase CLI. Example: tomhoule/test-project@main."
     required: true
-  schema_path:
+  schema-path:
     description: The file path of the schema to check, as GraphQL SDL.
     required: true
-  subgraph_name:
+  subgraph-name:
     description: The name of the subgraph to check. Only required in federated projects.
-  slack_incoming_webhook_url:
+  slack-incoming-webhook-url:
     description: An optional Slack webhook url to post errors to
 
 
@@ -26,12 +26,12 @@ runs:
     - id: validate-args
       shell: bash
       env:
-        SCHEMA_PATH: "${{ inputs.schema_path }}"
+        SCHEMA_PATH: "${{ inputs.schema-path }}"
       run: |
         : Handle the inputs.
 
         if [ -z "$SCHEMA_PATH" ]; then
-          echo "The schema_path input is missing."
+          echo "The schema-path input is missing."
           exit 1
         fi
 
@@ -40,13 +40,13 @@ runs:
           exit 1
         fi
 
-        if [ -z "${{ inputs.grafbase_access_token }}" ]; then
-          echo "The grafbase_access_token input is missing."
+        if [ -z "${{ inputs.grafbase-access-token }}" ]; then
+          echo "The grafbase-access-token input is missing."
           exit 1
         fi
 
-        if [ -z "${{ inputs.project_ref }}" ]; then
-          echo "The project_ref input is missing."
+        if [ -z "${{ inputs.project-ref }}" ]; then
+          echo "The project-ref input is missing."
           exit 1
         fi
 
@@ -62,20 +62,20 @@ runs:
     - id: check
       shell: bash
       env:
-        SCHEMA_PATH: ${{ inputs.schema_path }}
-        GRAFBASE_ACCESS_TOKEN: ${{ inputs.grafbase_access_token }}
+        SCHEMA_PATH: ${{ inputs.schema-path }}
+        GRAFBASE_ACCESS_TOKEN: ${{ inputs.grafbase-access-token }}
       run: |
         : Perform the check
 
-        if [ -n "${{ inputs.subgraph_name }}" ]; then
-          SUBGRAPH="--subgraph ${{ inputs.subgraph_name }}"
+        if [ -n "${{ inputs.subgraph-name }}" ]; then
+          SUBGRAPH="--subgraph ${{ inputs.subgraph-name }}"
         else
           SUBGRAPH=""
         fi
 
         set +e
         echo 'check_errors<<STOPHERE' > "$GITHUB_OUTPUT"
-        npx grafbase check "${{ inputs.project_ref }}" --schema "$SCHEMA_PATH" $SUBGRAPH |& tee >(cat >&2) | jq --slurp --raw-input >> "$GITHUB_OUTPUT"
+        npx grafbase check "${{ inputs.project-ref }}" --schema "$SCHEMA_PATH" $SUBGRAPH |& tee >(cat >&2) | jq --slurp --raw-input >> "$GITHUB_OUTPUT"
         exit_code=${PIPESTATUS[0]}
         echo 'STOPHERE' >> "$GITHUB_OUTPUT"
 
@@ -83,7 +83,7 @@ runs:
         exit $exit_code
 
     - name: Post check errors to slack
-      if: inputs.slack_incoming_webhook_url && failure()
+      if: inputs.slack-incoming-webhook-url && failure()
       uses: slackapi/slack-github-action@v1.24.0
       with:
         payload: |
@@ -107,5 +107,5 @@ runs:
             ]
           }
       env:
-        SLACK_WEBHOOK_URL: ${{ inputs.slack_incoming_webhook_url }}
+        SLACK_WEBHOOK_URL: ${{ inputs.slack-incoming-webhook-url }}
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
